import os
import numpy as np
from scipy.spatial.transform import Rotation as R
from datetime import datetime

def import_nodes(input_filename):
    nodes = []  # Initialize an empty list to store node data
    try:
        with open(input_filename, 'r') as file:
            # Iterate through each line in the file
            for line in file:
                # Skip the header line that contains 'phi1'
                if "phi1" in line:
                    continue
                # Split the line into components and strip whitespace
                parts = line.strip().split(',')
                # Parse each component as a float
                x = float(parts[0].strip())
                y = float(parts[1].strip())
                z = float(parts[2].strip())
                # Append the parsed values as a list to the nodes list
                nodes.append([x, y, z])
    except FileNotFoundError:
        print(f"Error: The file '{input_filename}' does not exist.")  # Handle file not found error
    except Exception as e:
        print(f"An error occurred while importing nodes: {e}")  # Handle any other exceptions
    # Return the nodes as a NumPy array
    return np.array(nodes)
def convert_radians_to_degrees(data):
    return np.degrees(data)  # Convert from radians to degrees
def convert_degrees_to_radians(data):
    return np.radians(data)  # Convert from degrees to radians
def compute_euler_angles(data_rad, read_order_orientation, output_order_orientation):
    orientlistR0 = []

    def normalize_angle(angle):
        return angle % 360

    # Iterate through each set of angles in the data
    for angles in data_rad:
        # Create a Rotation object using the 'zxz' convention, where input angles are in radians
        r = R.from_euler(read_order_orientation, angles, degrees=False)  # Use degrees=False because the input is in radians

        # Convert the rotation to Euler angles using the 'zxy' convention and output in degrees
        euler_angles = r.as_euler(output_order_orientation, degrees=True)  # Output Euler angles in degrees

        # Normalize each angle to ensure it's within the range [0, 360) degrees
        normalized_angles = [normalize_angle(angle) for angle in euler_angles]

        # Append the normalized Euler angles to the list
        orientlistR0.append(normalized_angles)

    return orientlistR0
def write_data_to_file(filename, orientlistR0, grain_index, start_index, output_orientation_filename, number_of_grains, orientation_header):
    current_date = datetime.now().strftime("%Y-%m-%d")
    with open(filename, 'w') as file:
        file.write(f'/com    Generated by Python 3.12  {current_date}')
        file.write(orientation_header)

        # Write Euler angles in the specified format
        for i, angles in enumerate(orientlistR0, start=start_index):
            # Format each line according to the specified format
            line = f'local,{i},0.,0.,0.,0.,{angles[0]:.3f},{angles[1]:.3f},{angles[2]:.3f}\n'
            file.write(line)

        # Write additional information for each grain

        for i, angles in enumerate(orientlistR0, start=start_index):
            file.write(f'CMSEL,s,Grain_{grain_index},ELEM\n')
            file.write(f'emod, Grain_{grain_index}, esys, {i}\n')
            file.write(f'/com,******************************\n')
            grain_index += 1

    if number_of_grains != (grain_index - 1):
        os.remove(filename)
        print("Error: The number of grains do not match the number of orientations")
    else:
        print(f"File '{output_orientation_filename}' has been saved")
def orientation(input_file, grain_index, start_index, output_file, orientation_filename, output_orientation_filename, number_of_grains, orientation_header, read_order_orientation, output_order_orientation):
    input_filename = f'{input_file}/{orientation_filename}'
    output_filename = f'{output_file}/{output_orientation_filename}'

    # Import orientation data
    data = import_nodes(input_filename)

    # Convert the angles from radians to degrees and then back to radians (for consistency in processing)
    data_degrees = convert_radians_to_degrees(data)
    reducedOri_rad = convert_degrees_to_radians(data_degrees)  # Note: This step may be redundant

    # Compute Euler angles
    orientlistR0 = compute_euler_angles(reducedOri_rad, read_order_orientation, output_order_orientation)

    # Write the data to a new file in the specified format
    write_data_to_file(output_filename, orientlistR0, grain_index, start_index, output_orientation_filename, number_of_grains, orientation_header)
